In [1]:
import numpy as np
import logging
import math
import pandas as pd
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [2]:
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [4]:
output_path = "/home/ashish/Results/Datasets/Shimmer/MP/ManualStd/103007/"

In [5]:
train_df = pd.read_csv(output_path + "train_default.csv")
test_df = pd.read_csv(output_path + "test_default.csv")
train_df = shuffle(train_df)
test_df = shuffle(test_df)

In [6]:
train_df.head()

0         1         2         3         4             5    6    7  \
1376  16 -1.564618 -0.716527  0.638926 -0.009444 -1.563194e-16  1.0  1.0   
1067  26 -1.678563 -0.726076  0.643139  0.120680 -8.810730e-16  1.0  1.0   
487   14 -1.433422 -0.675575  0.539146 -0.122588 -4.192202e-16  1.0  1.0   
1313  22 -1.696039 -0.651949  0.623066 -0.062335  3.774758e-16  1.0  1.0   
122   19 -1.637804 -0.690133  0.591804 -0.011363  2.291500e-16  1.0  1.0   

             8         9  ...      1252      1253      1254      1255  \
1376  0.824952 -2.201927  ...  2.259081  3.721291 -0.700087  0.655021   
1067  0.804992 -2.350703  ...  1.386505  4.202991  0.664435 -1.009919   
487   0.796194 -1.957041  ...  1.036123  3.319753 -0.607670 -0.952063   
1313  0.772510 -2.250611  ...  2.880918  4.233232  1.437330  1.494976   
122   0.783122 -2.591151  ...  1.848623  4.078577 -0.902219 -0.089117   

          1256      1257      1258  1259  1260  1261  
1376  1.943817  0.000101  1.011084   1.0   P16     N  
1067  2.371429  0.000347  1.016882   1.0   P48     A  
487   2.192791  0.000150  1.013307   1.0   P23     N  
1313  2.364116  0.000108  1.014687   1.0    P4     N  
122   2.163682  0.001163  1.020685   1.0   P54     R  

[5 rows x 1262 columns]

In [7]:
train_df.shape, test_df.shape

((1426, 1262), (595, 1262))

In [8]:
train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

In [9]:
train_X.head()

0         1         2         3         4             5    6    7  \
1376  16 -1.564618 -0.716527  0.638926 -0.009444 -1.563194e-16  1.0  1.0   
1067  26 -1.678563 -0.726076  0.643139  0.120680 -8.810730e-16  1.0  1.0   
487   14 -1.433422 -0.675575  0.539146 -0.122588 -4.192202e-16  1.0  1.0   
1313  22 -1.696039 -0.651949  0.623066 -0.062335  3.774758e-16  1.0  1.0   
122   19 -1.637804 -0.690133  0.591804 -0.011363  2.291500e-16  1.0  1.0   

             8         9  ...      1250      1251      1252      1253  \
1376  0.824952 -2.201927  ...  0.852828 -1.462210  2.259081  3.721291   
1067  0.804992 -2.350703  ...  0.813584 -2.816487  1.386505  4.202991   
487   0.796194 -1.957041  ...  0.858449 -2.283630  1.036123  3.319753   
1313  0.772510 -2.250611  ...  0.744104 -1.352314  2.880918  4.233232   
122   0.783122 -2.591151  ...  0.869183 -2.229954  1.848623  4.078577   

          1254      1255      1256      1257      1258  1259  
1376 -0.700087  0.655021  1.943817  0.000101  1.011084   1.0  
1067  0.664435 -1.009919  2.371429  0.000347  1.016882   1.0  
487  -0.607670 -0.952063  2.192791  0.000150  1.013307   1.0  
1313  1.437330  1.494976  2.364116  0.000108  1.014687   1.0  
122  -0.902219 -0.089117  2.163682  0.001163  1.020685   1.0  

[5 rows x 1260 columns]

In [10]:
train_Y.head()

1376    N
1067    A
487     N
1313    N
122     R
Name: 1261, dtype: object

In [11]:
regressor = RandomForestClassifier(n_estimators=200, random_state=0)
regressor.fit(train_X, train_Y)
pred_Y = regressor.predict(test_X)

In [12]:
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

In [13]:
print(accuracy), print(confusion_matrix), print(classification_report)

0.7798319327731092
[[129   5  14   2]
 [ 32  90  18   0]
 [ 36   1 110   3]
 [  6   1  13 135]]
              precision    recall  f1-score   support

           A       0.64      0.86      0.73       150
        Arch       0.93      0.64      0.76       140
           N       0.71      0.73      0.72       150
           R       0.96      0.87      0.92       155

    accuracy                           0.78       595
   macro avg       0.81      0.78      0.78       595
weighted avg       0.81      0.78      0.78       595



(None, None, None)

In [14]:
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [15]:
regressor = RandomForestClassifier(random_state=0)
regressor.fit(train_X, train_Y)
pred_Y = regressor.predict(test_X)
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)
print(accuracy), print(confusion_matrix), print(classification_report)

0.7680672268907563
[[118   9  20   3]
 [ 30  90  19   1]
 [ 34   3 112   1]
 [  6   0  12 137]]
              precision    recall  f1-score   support

           A       0.63      0.79      0.70       150
        Arch       0.88      0.64      0.74       140
           N       0.69      0.75      0.72       150
           R       0.96      0.88      0.92       155

    accuracy                           0.77       595
   macro avg       0.79      0.77      0.77       595
weighted avg       0.79      0.77      0.77       595



(None, None, None)

In [16]:
regressor = RandomForestClassifier(n_estimators=400, random_state=0)
regressor.fit(train_X, train_Y)
pred_Y = regressor.predict(test_X)
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)
print(accuracy), print(confusion_matrix), print(classification_report)

0.7798319327731092
[[117   7  24   2]
 [ 25  91  23   1]
 [ 29   1 117   3]
 [  5   0  11 139]]
              precision    recall  f1-score   support

           A       0.66      0.78      0.72       150
        Arch       0.92      0.65      0.76       140
           N       0.67      0.78      0.72       150
           R       0.96      0.90      0.93       155

    accuracy                           0.78       595
   macro avg       0.80      0.78      0.78       595
weighted avg       0.80      0.78      0.78       595



(None, None, None)