In [74]:
import numpy as np
import logging
import math
import pandas as pd
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [141]:
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

In [265]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

In [264]:
output_path = "/home/ashish/Results/Datasets/Shimmer/MP/Manual/103007/"
data_type = "default"
SEED_VALUES = [103007, 1899797, 191099]

In [204]:
n_estimators = [int(x) for x in np.linspace(start = 50, stop = 600, num = 8)]
# max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
# max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
# max_depth.append(None)
# Minimum number of samples required to split a node
# min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
# min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
# bootstrap = [True, False]

random_grid = {'n_estimators': n_estimators,
               # 'max_features': max_features,
               # 'max_depth': max_depth,
               # 'min_samples_split': min_samples_split,
               # 'min_samples_leaf': min_samples_leaf,
               # 'bootstrap': bootstrap
              }

In [205]:
n_estimators

[50, 128, 207, 285, 364, 442, 521, 600]

In [207]:
data_type

'default_9'

In [210]:
data_type = "default"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

regressor = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 6, cv = 3, verbose=2, 
                               random_state=42, n_jobs = -1)
rf_random.fit(train_X, train_Y)
pred_Y = rf_random.predict(test_X)

print(rf_random.best_params_)

accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)

(1426, 1262) (595, 1262)
Fitting 3 folds for each of 6 candidates, totalling 18 fits
{'n_estimators': 207}
0.7865546218487395
[[124   5  17   4]
 [ 26  95  19   0]
 [ 34   1 112   3]
 [  5   1  12 137]]
              precision    recall  f1-score   support

           A       0.66      0.83      0.73       150
        Arch       0.93      0.68      0.79       140
           N       0.70      0.75      0.72       150
           R       0.95      0.88      0.92       155

    accuracy                           0.79       595
   macro avg       0.81      0.78      0.79       595
weighted avg       0.81      0.79      0.79       595



(None, None, None)

In [212]:
data_type = "default_9"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

regressor = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 6, cv = 3, verbose=2, 
                               random_state=42, n_jobs = -1)
rf_random.fit(train_X, train_Y)
pred_Y = rf_random.predict(test_X)
print(rf_random.best_params_)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)

(1426, 812) (595, 812)
Fitting 3 folds for each of 6 candidates, totalling 18 fits
{'n_estimators': 207}
0.7815126050420168
[[118   8  20   4]
 [ 28  99  12   1]
 [ 30   3 114   3]
 [  6   1  14 134]]
              precision    recall  f1-score   support

           A       0.65      0.79      0.71       150
        Arch       0.89      0.71      0.79       140
           N       0.71      0.76      0.74       150
           R       0.94      0.86      0.90       155

    accuracy                           0.78       595
   macro avg       0.80      0.78      0.78       595
weighted avg       0.80      0.78      0.79       595



(None, None, None)

In [215]:
data_type = "larabk"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

random_grid = {'n_estimators': [50, 128, 207, 285, 364, 442, 521, 600, 800, 1000]}

regressor = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 7, cv = 3, verbose=2, 
                               random_state=42, n_jobs = -1)
rf_random.fit(train_X, train_Y)
pred_Y = rf_random.predict(test_X)
print(rf_random.best_params_)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)

(1426, 758) (595, 758)
Fitting 3 folds for each of 7 candidates, totalling 21 fits
{'n_estimators': 442}
0.7361344537815127
[[119   7  15   9]
 [ 29  82  26   3]
 [ 30   4 109   7]
 [ 15   0  12 128]]
              precision    recall  f1-score   support

           A       0.62      0.79      0.69       150
        Arch       0.88      0.59      0.70       140
           N       0.67      0.73      0.70       150
           R       0.87      0.83      0.85       155

    accuracy                           0.74       595
   macro avg       0.76      0.73      0.74       595
weighted avg       0.76      0.74      0.74       595



(None, None, None)

In [216]:
data_type = "lara"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

random_grid = {'n_estimators': [50, 128, 207, 285, 364, 442, 521, 600, 800, 1000]}

regressor = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 7, cv = 3, verbose=2, 
                               random_state=42, n_jobs = -1)
rf_random.fit(train_X, train_Y)
pred_Y = rf_random.predict(test_X)
print(rf_random.best_params_)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)

(1426, 506) (595, 506)
Fitting 3 folds for each of 7 candidates, totalling 21 fits
{'n_estimators': 1000}
0.7210084033613445
[[108  20  15   7]
 [ 22  79  36   3]
 [ 17   7 110  16]
 [ 10   2  11 132]]
              precision    recall  f1-score   support

           A       0.69      0.72      0.70       150
        Arch       0.73      0.56      0.64       140
           N       0.64      0.73      0.68       150
           R       0.84      0.85      0.84       155

    accuracy                           0.72       595
   macro avg       0.72      0.72      0.72       595
weighted avg       0.72      0.72      0.72       595



(None, None, None)

In [224]:
data_type = "bk"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

random_grid = {'n_estimators': [50, 128, 207, 285, 364, 442, 521, 600, 800, 1000]}

regressor = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 7, cv = 3, verbose=2, 
                               random_state=42, n_jobs = -1)
rf_random.fit(train_X, train_Y)
pred_Y = rf_random.predict(test_X)
print(rf_random.best_params_)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)

(1426, 254) (595, 254)
Fitting 3 folds for each of 7 candidates, totalling 21 fits
{'n_estimators': 600}
0.5327731092436975
[[86  8 20 36]
 [43 70 15 12]
 [34 10 92 14]
 [63  7 16 69]]
              precision    recall  f1-score   support

           A       0.38      0.57      0.46       150
        Arch       0.74      0.50      0.60       140
           N       0.64      0.61      0.63       150
           R       0.53      0.45      0.48       155

    accuracy                           0.53       595
   macro avg       0.57      0.53      0.54       595
weighted avg       0.57      0.53      0.54       595



(None, None, None)

In [227]:
data_type = "default"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

# sc = StandardScaler()
# train_X = sc.fit_transform(train_X)
# test_X = sc.transform(test_X)





model = GaussianNB()
model.fit(train_X, train_Y)
pred_Y = model.predict(test_X)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)



(1426, 1262) (595, 1262)
0.6521008403361345
[[ 99  20  30   1]
 [ 16  87  35   2]
 [ 40  11  86  13]
 [  9   1  29 116]]
              precision    recall  f1-score   support

           A       0.60      0.66      0.63       150
        Arch       0.73      0.62      0.67       140
           N       0.48      0.57      0.52       150
           R       0.88      0.75      0.81       155

    accuracy                           0.65       595
   macro avg       0.67      0.65      0.66       595
weighted avg       0.67      0.65      0.66       595



(None, None, None)

In [255]:
data_type = "default"
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)





model = svm.SVC(kernel='linear', C=0.001) 
model.fit(train_X, train_Y)
pred_Y = model.predict(test_X)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)



(1426, 1262) (595, 1262)
0.8369747899159664
[[116  11  23   0]
 [ 16 113  11   0]
 [ 18   4 125   3]
 [  6   2   3 144]]
              precision    recall  f1-score   support

           A       0.74      0.77      0.76       150
        Arch       0.87      0.81      0.84       140
           N       0.77      0.83      0.80       150
           R       0.98      0.93      0.95       155

    accuracy                           0.84       595
   macro avg       0.84      0.84      0.84       595
weighted avg       0.84      0.84      0.84       595



(None, None, None)

In [294]:
data_type = "larabk"
output_path = "/home/ashish/Results/Datasets/Shimmer/Rowing/Manual/103007/"

train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))
print(train_df.shape, test_df.shape)
train_df = shuffle(train_df)
test_df = shuffle(test_df)

train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)



model = LogisticRegression(C=0.001)  #KNeighborsClassifier(n_neighbors=80) 
model.fit(train_X, train_Y)
pred_Y = model.predict(test_X)


accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

print(accuracy), print(confusion_matrix), print(classification_report)



(1773, 758) (760, 758)
0.6631578947368421
[[ 85   9  28  25  13]
 [  0 137  10   2   1]
 [ 43   6  91   8   2]
 [ 20   6  32  91  11]
 [ 18   1  10  11 100]]
              precision    recall  f1-score   support

           A       0.51      0.53      0.52       160
         Ext       0.86      0.91      0.89       150
           N       0.53      0.61      0.57       150
           R       0.66      0.57      0.61       160
          RB       0.79      0.71      0.75       140

    accuracy                           0.66       760
   macro avg       0.67      0.67      0.67       760
weighted avg       0.67      0.66      0.66       760



(None, None, None)

In [271]:
output_path = "/home/ashish/Results/Datasets/Shimmer/MP/Manual/{}/"
data_type = "default"

avg_acc = []
for sv in SEED_VALUES:
    train_df = pd.read_csv(output_path.format(sv) + "train_{}.csv".format(data_type))
    test_df = pd.read_csv(output_path.format(sv) + "test_{}.csv".format(data_type))
    train_df = shuffle(train_df)
    test_df = shuffle(test_df)

    train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
    test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

    sc = StandardScaler()
    train_X = sc.fit_transform(train_X)
    test_X = sc.transform(test_X)


    model = LogisticRegression(C=0.001, max_iter=150) 
    model.fit(train_X, train_Y)
    pred_Y = model.predict(test_X)


    accuracy = metrics.accuracy_score(test_Y, pred_Y)
    confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
    classification_report = metrics.classification_report(test_Y, pred_Y)

    print(accuracy) #, print(confusion_matrix), print(classification_report)
    avg_acc.append(accuracy)

print(round(np.mean(avg_acc),2), np.std(avg_acc))

0.8352941176470589
0.7897526501766784
0.8338815789473685
0.82 0.021143380575338686


In [304]:
output_path = "/home/ashish/Results/Datasets/Shimmer/MP/Manual/{}/"
data_type = "default_noscale"

avg_acc = []
for sv in SEED_VALUES:
    train_df = pd.read_csv(output_path.format(sv) + "train_{}.csv".format(data_type))
    test_df = pd.read_csv(output_path.format(sv) + "test_{}.csv".format(data_type))
    train_df = shuffle(train_df)
    test_df = shuffle(test_df)

    train_X, train_Y = train_df.iloc[:, :-2], train_df.iloc[:, -1]
    test_X, test_Y = test_df.iloc[:, :-2], test_df.iloc[:, -1]

    sc = StandardScaler()
    train_X = sc.fit_transform(train_X)
    test_X = sc.transform(test_X)


    # regressor = RandomForestClassifier()
    # model = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid, n_iter = 7, cv = 3, verbose=2, 
    #                            random_state=42, n_jobs = -1)
    # svm.SVC(kernel='linear', C=0.001)  LogisticRegression(C=0.001, max_iter=150)   KNeighborsClassifier(n_neighbors=40) 
    model = LogisticRegression(C=0.001, max_iter=150)
    model.fit(train_X, train_Y)
    pred_Y = model.predict(test_X)


    accuracy = metrics.accuracy_score(test_Y, pred_Y)
    confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
    classification_report = metrics.classification_report(test_Y, pred_Y)

    print(accuracy) #, print(confusion_matrix), print(classification_report)
    avg_acc.append(accuracy)

print(round(np.mean(avg_acc),2), np.std(avg_acc))

0.7798319327731092
0.7879858657243817
0.8388157894736842
0.8 0.02609653685454943


In [138]:
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)

In [139]:
print(accuracy), print(confusion_matrix), print(classification_report)

0.761344537815126
[[105   9  24  12]
 [ 24 105   2   9]
 [ 30   1 106  13]
 [ 11   5   2 137]]
              precision    recall  f1-score   support

           A       0.62      0.70      0.66       150
        Arch       0.88      0.75      0.81       140
           N       0.79      0.71      0.75       150
           R       0.80      0.88      0.84       155

    accuracy                           0.76       595
   macro avg       0.77      0.76      0.76       595
weighted avg       0.77      0.76      0.76       595



(None, None, None)

In [305]:
def generate_cross_val_splits(pid):
    

'/home/ashish/Results/Datasets/Shimmer/MP/Manual/{}/'

In [313]:



print(len(unique_pids))

(1426, 506) (595, 506) (2021, 506)
52


In [336]:
def generate_cross_val_splits(pid):
    second_last_col = full_df.columns[-2]
    pid_excl_df = full_df[full_df[second_last_col]!=pid]
    pid_incl_df = full_df[full_df[second_last_col]==pid]
        
    train_X, train_Y = pid_excl_df.iloc[:, :-2], pid_excl_df.iloc[:, -1]
    test_X, test_Y = pid_incl_df.iloc[:, :-2], pid_incl_df.iloc[:, -1]
    
    return train_X, train_Y, test_X, test_Y

In [328]:
print(train_df.shape, test_df.shape, full_df.shape)


(1426, 1262) (595, 1262) (2021, 1262)


In [330]:
pid_excl_df = full_df[full_df["504"]!="P10"]
pid_excl_df.shape

(2021, 1262)

In [331]:
pid_excl_df.head()

0         1         2          3          4          5         6  \
531  18  6.577275  8.371956  12.015875  10.117646  10.245446  2.431676   
466  20  8.793942  9.062770   9.723990   9.350636   9.467738  0.605215   
91   22  8.743281  9.282771  10.570614   9.930723   9.908146  0.782619   
126  26  7.782738  8.911906  10.673242   9.978836   9.810669  1.171943   
225  22  8.866331  9.351444  10.532357   9.975083   9.953648  0.699158   

            7          8         9  ...      1252      1253      1254  \
531  5.913048  10.245446  4.966917  ...  0.868024  0.116749 -0.910637   
466  0.366285   9.467738  8.008791  ...  0.853918  0.052386  1.118411   
91   0.612493   9.908146  8.314539  ...  0.825022  0.037539 -1.348771   
126  1.373450   9.810669  6.992861  ...  1.040538  0.154117 -1.483770   
225  0.488822   9.953648  8.123906  ...  0.970492  0.192694 -1.296100   

         1255      1256          1257      1258      1259  1260  1261  
531 -0.687159  0.002679  3.430844e-08  1.011363  0.681418   P10     N  
466 -1.159124  0.000313  1.204017e-07  1.019061  0.700337   P37     R  
91  -0.385153  0.000220  3.242991e-07  1.022837  0.653965   P19     A  
126 -0.352908  0.006161  7.850378e-07  1.020415  0.952686   P22     R  
225  0.523335  0.009480  8.799055e-07  1.019061  0.731958   P31  Arch  

[5 rows x 1262 columns]

In [339]:
data_type = "default_noscale"
output_path = '/home/ashish/Results/Datasets/Shimmer/Rowing/Manual/103007/'
train_df = pd.read_csv(output_path + "train_{}.csv".format(data_type))
test_df = pd.read_csv(output_path + "test_{}.csv".format(data_type))


full_df = pd.concat([train_df, test_df], axis=0)

# train_df = shuffle(train_df)
# test_df = shuffle(test_df)
full_df = shuffle(full_df)

print(train_df.shape, test_df.shape, full_df.shape)


scores = []
accuracy_scores_mapping = {"pid": [], "score": []}


model = LogisticRegression(C=0.001, max_iter=150)

unique_pids = list(np.unique(full_df.iloc[:, -2]))

for pid in unique_pids:
    logger.info("The pid: {} ".format(pid))
    accuracy_scores_mapping["pid"].append(pid)
    train_X, train_Y, test_X, test_Y = generate_cross_val_splits(pid)
    logger.info("Training shape: {} {}".format(train_X.shape, train_Y.shape))
    logger.info("Testing shape: {} {}".format(test_X.shape, test_Y.shape))
    
    sc = StandardScaler()
    train_X = sc.fit_transform(train_X)
    test_X = sc.transform(test_X)

    model.fit(train_X, train_Y)

    pred_Y = model.predict(test_X)
    accuracy = metrics.accuracy_score(test_Y, pred_Y)
    
    scores.append(accuracy)
    accuracy_scores_mapping["score"].append(accuracy)
    logger.info("The accuracy: {} ".format(accuracy))
accuracy_scores_mapping_df = pd.DataFrame(accuracy_scores_mapping)
accuracy_scores_mapping_df.to_csv("/tmp/accuracy_cross_val_shimmer_mp_manual.csv", index=False)
logger.info("The average accuracy: {} std: {}".format(np.mean(scores), np.std(scores)))

INFO:__main__:The pid: P10 
INFO:__main__:Training shape: (2483, 1260) (2483,)
INFO:__main__:Testing shape: (50, 1260) (50,)


(1773, 1262) (760, 1262) (2533, 1262)


INFO:__main__:The accuracy: 0.92 
INFO:__main__:The pid: P11 
INFO:__main__:Training shape: (2483, 1260) (2483,)
INFO:__main__:Testing shape: (50, 1260) (50,)
INFO:__main__:The accuracy: 0.68 
INFO:__main__:The pid: P12 
INFO:__main__:Training shape: (2481, 1260) (2481,)
INFO:__main__:Testing shape: (52, 1260) (52,)
INFO:__main__:The accuracy: 0.7115384615384616 
INFO:__main__:The pid: P13 
INFO:__main__:Training shape: (2483, 1260) (2483,)
INFO:__main__:Testing shape: (50, 1260) (50,)
INFO:__main__:The accuracy: 0.96 
INFO:__main__:The pid: P14 
INFO:__main__:Training shape: (2483, 1260) (2483,)
INFO:__main__:Testing shape: (50, 1260) (50,)
INFO:__main__:The accuracy: 0.86 
INFO:__main__:The pid: P15 
INFO:__main__:Training shape: (2493, 1260) (2493,)
INFO:__main__:Testing shape: (40, 1260) (40,)
INFO:__main__:The accuracy: 0.675 
INFO:__main__:The pid: P16 
INFO:__main__:Training shape: (2483, 1260) (2483,)
INFO:__main__:Testing shape: (50, 1260) (50,)
INFO:__main__:The accuracy: 0.8

In [142]:
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [144]:
regressor = RandomForestClassifier(random_state=0)
regressor.fit(train_X, train_Y)
pred_Y = regressor.predict(test_X)
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)
print(accuracy), print(confusion_matrix), print(classification_report)

0.773109243697479
[[105  13  21  11]
 [ 25 104   2   9]
 [ 26   1 112  11]
 [  7   6   3 139]]
              precision    recall  f1-score   support

           A       0.64      0.70      0.67       150
        Arch       0.84      0.74      0.79       140
           N       0.81      0.75      0.78       150
           R       0.82      0.90      0.86       155

    accuracy                           0.77       595
   macro avg       0.78      0.77      0.77       595
weighted avg       0.78      0.77      0.77       595



(None, None, None)

In [145]:
regressor = RandomForestClassifier(n_estimators=400, random_state=0)
regressor.fit(train_X, train_Y)
pred_Y = regressor.predict(test_X)
accuracy = metrics.accuracy_score(test_Y, pred_Y)
confusion_matrix = metrics.confusion_matrix(test_Y, pred_Y)
classification_report = metrics.classification_report(test_Y, pred_Y)
print(accuracy), print(confusion_matrix), print(classification_report)

0.7680672268907563
[[112   7  19  12]
 [ 25 105   1   9]
 [ 32   1 104  13]
 [ 11   6   2 136]]
              precision    recall  f1-score   support

           A       0.62      0.75      0.68       150
        Arch       0.88      0.75      0.81       140
           N       0.83      0.69      0.75       150
           R       0.80      0.88      0.84       155

    accuracy                           0.77       595
   macro avg       0.78      0.77      0.77       595
weighted avg       0.78      0.77      0.77       595



(None, None, None)

In [151]:
c = ['B8C7_Accel_Magnitude', 'B8C7_Gyro_Magnitude', 'B8C7_pitch', 'B8C7_roll', 'B8C7_yaw', 'B8E3_Accel_Magnitude', 'B8E3_Gyro_Magnitude', 'B8E3_Waist_Accel_LN_X', 'B8E3_Waist_Accel_LN_Y', 'B8E3_Waist_Accel_LN_Z', 'B8E3_Waist_Gyro_X', 'B8E3_Waist_Gyro_Y', 'B8E3_Waist_Gyro_Z', 'B8E3_Waist_Mag_X', 'B8E3_Waist_Mag_Y', 'B8E3_Waist_Mag_Z', 'B8E3_pitch', 'B8E3_roll', 'B8E3_yaw', 'S548D_Accel_Magnitude', 'S548D_Gyro_Magnitude', 'S548D_Left_Accel_LN_X', 'S548D_Left_Accel_LN_Y', 'S548D_Left_Accel_LN_Z', 'S548D_Left_Gyro_X', 'S548D_Left_Gyro_Y', 'S548D_Left_Gyro_Z', 'S548D_Left_Mag_X', 'S548D_Left_Mag_Y', 'S548D_Left_Mag_Z', 'S548D_pitch', 'S548D_roll', 'S548D_yaw', 'S57D0Waist_Accel_LN_X', 'S57D0Waist_Accel_LN_Y', 'S57D0Waist_Accel_LN_Z', 'S57D0Waist_Gyro_X', 'S57D0Waist_Gyro_Y', 'S57D0Waist_Gyro_Z', 'S57D0Waist_Mag_X', 'S57D0Waist_Mag_Y', 'S57D0Waist_Mag_Z', 'S57D0_Accel_Magnitude', 'S57D0_Gyro_Magnitude', 'S57D0_pitch', 'S57D0_roll', 'S57D0_yaw', 'S9276_Accel_LN_X', 'S9276_Accel_LN_Y', 'S9276_Accel_LN_Z', 'S9276_Accel_Magnitude', 'S9276_Gyro_Magnitude', 'S9276_Gyro_X', 'S9276_Gyro_Y', 'S9276_Gyro_Z', 'S9276_Mag_X', 'S9276_Mag_Y', 'S9276_Mag_Z', 'S9276_pitch', 'S9276_roll', 'S9276_yaw', 'Shimmer_B8C7_Accel_LN_X', 'Shimmer_B8C7_Accel_LN_Y', 'Shimmer_B8C7_Accel_LN_Z', 'Shimmer_B8C7_Gyro_X', 'Shimmer_B8C7_Gyro_Y', 'Shimmer_B8C7_Gyro_Z', 'Shimmer_B8C7_Mag_X', 'Shimmer_B8C7_Mag_Y', 'Shimmer_B8C7_Mag_Z']


In [154]:
"Shimmer_B8C7_Mag_Z".replace("Shimmer_", "")

'B8C7_Mag_Z'

In [163]:
re = []

for col in c:
    for p in ["_Waist", "LN", "Shimmer_", "Left", "Waist"]:
        col = col.replace(p, "")
    col = col.replace("__", "_")
    re.append(col)

In [165]:
print(re)

['B8C7_Accel_Magnitude', 'B8C7_Gyro_Magnitude', 'B8C7_pitch', 'B8C7_roll', 'B8C7_yaw', 'B8E3_Accel_Magnitude', 'B8E3_Gyro_Magnitude', 'B8E3_Accel_X', 'B8E3_Accel_Y', 'B8E3_Accel_Z', 'B8E3_Gyro_X', 'B8E3_Gyro_Y', 'B8E3_Gyro_Z', 'B8E3_Mag_X', 'B8E3_Mag_Y', 'B8E3_Mag_Z', 'B8E3_pitch', 'B8E3_roll', 'B8E3_yaw', 'S548D_Accel_Magnitude', 'S548D_Gyro_Magnitude', 'S548D_Accel_X', 'S548D_Accel_Y', 'S548D_Accel_Z', 'S548D_Gyro_X', 'S548D_Gyro_Y', 'S548D_Gyro_Z', 'S548D_Mag_X', 'S548D_Mag_Y', 'S548D_Mag_Z', 'S548D_pitch', 'S548D_roll', 'S548D_yaw', 'S57D0_Accel_X', 'S57D0_Accel_Y', 'S57D0_Accel_Z', 'S57D0_Gyro_X', 'S57D0_Gyro_Y', 'S57D0_Gyro_Z', 'S57D0_Mag_X', 'S57D0_Mag_Y', 'S57D0_Mag_Z', 'S57D0_Accel_Magnitude', 'S57D0_Gyro_Magnitude', 'S57D0_pitch', 'S57D0_roll', 'S57D0_yaw', 'S9276_Accel_X', 'S9276_Accel_Y', 'S9276_Accel_Z', 'S9276_Accel_Magnitude', 'S9276_Gyro_Magnitude', 'S9276_Gyro_X', 'S9276_Gyro_Y', 'S9276_Gyro_Z', 'S9276_Mag_X', 'S9276_Mag_Y', 'S9276_Mag_Z', 'S9276_pitch', 'S9276_roll', 